name: publish

on: push

jobs:
  arch:
    runs-on: ubuntu-latest

    container: archlinux:latest

    steps:
      - uses: actions/checkout@v2

      - run: ls
      - run: pwd
      - run: whoami
      - run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git openssh

      - run: 'mkdir ~/.ssh; echo "$SSH_KEY" > ~/.ssh/id_rsa'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.AUR_SSH_KEY }}

      - run: 'cat ~/.ssh/id_rsa'
        shell: bash
